**Exercise:**

Generate a 5x5 matrix, with values 1, 2, 3, 4, 5 on the diagonal, 0 elsewhere, in **one line of code**.

In [1]:
import numpy as np

np.arange(1, 6)*np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

**Exercise:**
    
- Generate an array with values from 0 to 8.
- Display values 1 to 6.
- Set values 6 to 8 to 22 and display the array.

In [2]:
arr = np.arange(9)
print(arr[1:7])

[1 2 3 4 5 6]


In [4]:
arr[6:] = 22
print(arr)

[ 0  1  2  3  4  5 22 22 22]


**Exercise:**
    
Create a 5x5 matrix with values ranging from 0 to 24. Display the 3x3 inside submatrix.

In [5]:
matrix = np.arange(25).reshape(5, 5)
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
sub_matrix = matrix[1:-1, 1:-1]
print(sub_matrix)

[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


**Exercise:**

Filter the movies in the imdb dataset with a star rating above 8. Then display the number of movies for each movie genre.

Conclude what movie genre should you produce to have a good rating.

In [8]:
import pandas as pd

movies = pd.read_csv('imdb_1000.csv')

good_rated_movies = movies[movies['star_rating']>8]
good_rated_movies['genre'].value_counts()

Drama        92
Crime        43
Comedy       38
Action       37
Adventure    25
Biography    20
Animation    18
Mystery       9
Western       7
Horror        5
Film-Noir     2
Sci-Fi        1
Name: genre, dtype: int64

This suggests drama movies are the best rated.

But a better indicator would be the ratio of each genre that are rated above 8:

In [11]:
(good_rated_movies['genre'].value_counts() / movies['genre'].value_counts()).sort_values(ascending=False)

Western      0.777778
Film-Noir    0.666667
Mystery      0.562500
Crime        0.346774
Adventure    0.333333
Drama        0.330935
Animation    0.290323
Action       0.272059
Biography    0.259740
Comedy       0.243590
Sci-Fi       0.200000
Horror       0.172414
Family            NaN
Fantasy           NaN
History           NaN
Thriller          NaN
Name: genre, dtype: float64

Now it seems Western movies are most likely to have good rating, while Family, Fantasy, History and Thriller movies never have a rating above 8 in our dataset.